Assignments/boolean birds
bhs-intro-to-programming/minaa12 pull request #1
Opened 2022-09-09 21:39 UTC by minaa12

2022-09-10 00:27 UTC, gigamonkey requested changes
Please fix the formatting issues (probably by running the reformatter in the editor as I described in one of the comments below) and fix the function definition syntax to the one I'm teaching you. When that's done you can add a comment to this PR with my Github handle (`@gigamonkey`) in it to let me know you're ready for another review.

2022-09-10 00:27 UTC, gigamonkey commented on assignments/boolean-birds/code.js
> +function isRed (s1){
Why did you suddenly switch to this syntax? It's legal Javascript but not the way I want you writing functions. Please change this and the following functions to use the same syntax you used for the functions above here.

2022-09-10 00:27 UTC, gigamonkey commented on assignments/boolean-birds/code.js
> +const isFlobbyBird= (red,spotted) => red&&spotted
These look good. As a matter of style you should put spaces around operators.

```suggestion
const isFlobbyBird = (red,spotted) => red && spotted;
```

It may seem a small thing but if code is consistently formatted it is much easier to spot problems. (As a hint, in the editor you can right click to pull up a menu that has an item "Format document" which will fix a lot of problems like this.

2022-09-13 22:01 UTC, minaa12 commented on assignments/boolean-birds/code.js
> +function isRed (s1){
I just fixed the syntax.

2022-09-14 01:06 UTC, gigamonkey approved these changes
Looks good! You can hit the big green Merge button now. Thanks!

2022-09-14 22:31 UTC, merged