Assignments/number functions
bhs-intro-to-programming/minaa12 pull request #2
Opened 2022-09-09 21:40 UTC by minaa12

2022-09-10 02:13 UTC, gigamonkey requested changes
Please fix `manhattanDistance` and `euclideanDistance` and then I'll approve this PR.

2022-09-10 02:13 UTC, gigamonkey commented on assignments/number-functions/code.js
> +const manhattanDistance= (x1,x2,y1,y2)=> Math.abs(x1-y1)+Math.abs(x2-y2)
This is a little odd. While it works you the way you named the arguments doesn't match up with their meaning. It would be better like this:

```suggestion
const manhattanDistance = (x1, y1, x2, y2)=> Math.abs(x1 - x2)+Math.abs(y1 - y2);
```

These names indicate to the reader that the first two arguments are one x,y point and the third and fourth are another x,y point. 

I see from the history of your changes that you originally had the right variable names but were subtracting the wrong values, e.g. x1 - y1. When you noticed that, you should have left the names in the argument list as they were and changed the code to subtract the x values from each other and the y values from each other.


You could also make this even clearer by using the `distance` function you just defined:

```suggestion
const manhattanDistance = (x1, y1, x2, y2)=> distance(x1, x2) + distance(y1, y2);
```

This capture the idea of the definition of Manhattan distance: it's the sum of the distances on each axis.

2022-09-10 02:13 UTC, gigamonkey commented on assignments/number-functions/code.js
> +const euclideanDistance= (x1,x2,y1,y2)=> Math.sqrt(Math.abs(x1-y1)**2+Math.abs(x2-y2)**2)
A mathematical note: you don't actually need `Math.abs` here since squaring a number already ensures that it's positive. Also, same problem with the names of the arguments not matching their meaning as in Manhattan distance.

2022-09-20 22:05 UTC, minaa12 commented on assignments/number-functions/code.js
> +const manhattanDistance= (x1,x2,y1,y2)=> Math.abs(x1-y1)+Math.abs(x2-y2)
just finished fixing that

2022-09-21 00:26 UTC, gigamonkey commented on assignments/number-functions/code.js
> +const manhattanDistance= (x1,x2,y1,y2)=> Math.abs(x1-y1)+Math.abs(x2-y2)
You still have the same problem in `euclideanDistance`.

2023-01-03 23:00 UTC, merged